### ISSUE TITLE
Doesn't seem to match the deuteranopia Photoshop filter

### ISSUE THREAD

**Issue by samjewell** [btholt/postcss-colorblind#10]
Hey, thanks for a cool project!

Sorry if this isn't very helpful, but just tried running our project through postcss-colorblind, and got very different results from what Photoshop gave me:

Normal colors:
![screen shot 2015-10-02 at 14 27 09](https://cloud.githubusercontent.com/assets/2903904/10247770/3b568044-6913-11e5-90cf-c6385c9c01d5.png)

postcss-colorblind:
![screen shot 2015-10-02 at 14 37 42](https://cloud.githubusercontent.com/assets/2903904/10247779/424be5e2-6913-11e5-87ea-6c412a3d7d7c.png)

Photoshop:
![screen shot 2015-10-02 at 14 38 50](https://cloud.githubusercontent.com/assets/2903904/10247790/52f497d6-6913-11e5-8199-d2350aee42de.png)

Any idea why that could be? Feels like a bug... Sorry not to have much more information on this yet...

**Comment by btholt** [comment]
Can you file this against [skratchdot/color-blind](https://github.com/skratchdot/color-blind)? That's the module actually doing the color transformations. But you're right, the color transform here is a little too zealous in the red direction.

**Comment by samjewell** [comment]
Hey, thanks, good tip. I ended up checking the hex codes that were coming out of skratchdot/color-blind just to make sure, but yes I completely agree, the issue lies there!

Cheers :-)

**Comment by btholt** [comment]
Seems like you and @skratchdot worked it out. That dude is sharp.
