### ISSUE TITLE
npm-gulp-postcss: hexa-color-regex bug

### ISSUE THREAD

**Issue by AliveDD** [btholt/postcss-colorblind#16]
**i'm install this plugin in my environment**

`var gulp = require('gulp');`
`var postcss = require('gulp-postcss');`
`var colorblind = require("postcss-colorblind");`

`var processors = [ colorblind({method:'achromatopsia'}) ];`
`return gulp.src(config.styles.src).pipe(postcss(processors));`

**and my terminal wrote me**

> module.js:328
>    throw err;
>    ^
>    Error: Cannot find module 'hexa-color-regex'
>     at Function.Module._resolveFilename (module.js:326:15)
>     at Function.Module._load (module.js:277:25)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/Users/eugene/Documents/git/tnved/node_modules/postcss-colorblind/src/color-transformer.js:8:12)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)

**I don't know what to do with this, I tried to delete the folder with node_modules**

**Comment by skratchdot** [comment]
Looks like this will be fixed with PR #13 .  In the meantime, just `npm install hexa-color-regex --save` in your repo to fix this.

**Comment by 1Copenut** [comment]
@skratchdot Thank you for the solution. I couldn't even get this error to the console. Tried gulp.plumber and on.error, but neither gave a clue. Adding the hexa-color-regex fixed it straight away.

**Comment by btholt** [comment]
Oh man, I didn't publish the fix. I'll get to it this weekend. Sorry about that.

**Comment by ben-eb** [comment]
Closed in https://github.com/btholt/postcss-colorblind/commit/b88822026e4bdca5f5aff332999e99357aad2f54.
