### ISSUE TITLE
Why only hex values?

### ISSUE THREAD

**Issue by lydell** [btholt/postcss-colorblind#2]
What about `rgb()`, `hsl()` and named colors?

One way could be to use the `onecolor` module. That module is already a dependency of `color-blind`, so npm should be able to dedupe which means that there will be no difference in the number of dependencies downloaded. If `onecolor(token) !== false` we can pass `token` to `color-blind`.

Also, you might want to use `postcss.list.space()` instead of `.split( )`.

**Comment by btholt** [comment]
It was a first pass but I definitely intend on supporting rgb, hsl, and rgba. It should already support named colors.

Also didn't know about that function. Thanks!

**Comment by btholt** [comment]
Addressed with rgb, rgba, hsl, and hsla with 62f8c77304e0b4e919f14409e6a3e636ae183646!

I'll look into the other function for future releases. Thanks!

**Comment by lydell** [comment]
Cool! :+1:
