### ISSUE TITLE
Versions mess

### ISSUE THREAD

**Issue by ai** [btholt/postcss-colorblind#5]
`package.json` contains `0.2.1`, but `CHANGELOG.md` `1.0`.

**Comment by btholt** [comment]
It is a mess. It probably should really be 1.0 because I broke the API. I'll fix it soon (I'm on vacation right now.)

**Comment by btholt** [comment]
Fixed! Rather than revision everything, I just released it as 0.2.1 and made 62f8c77304e0b4e919f14409e6a3e636ae183646 0.3.0. Thanks!
