### ISSUE TITLE
proplem when cloning this repo

### ISSUE THREAD

**Issue by cmnstmntmn** [btholt/postcss-colorblind#7]
`npm ERR! Command failed: git clone --template=/Users/ctin/.npm/_git-remotes/_templates --mirror ssh://git@github.com/btholt/hex-color-regex.git /Users/ctin/.npm/_git-remotes/ssh-git-github-com-btholt-hex-color-regex-git-2ab14d10 npm ERR! Cloning into bare repository '/Users/ctin/.npm/_git-remotes/ssh-git-github-com-btholt-hex-color-regex-git-2ab14d10'... npm ERR! Permission denied (publickey). npm ERR! fatal: Could not read from remote repository. npm ERR! npm ERR! Please make sure you have the correct access rights npm ERR! and the repository exists. npm ERR! npm ERR! npm ERR! If you need help, you may report this error at: npm ERR! <https://github.com/npm/npm/issues> npm ERR! Please include the following file with any support request: npm ERR! /Users/ctin/repos/gg/npm-debug.log`

**Comment by btholt** [comment]
Do you have your SSH keys set up? If not, [check here](https://help.github.com/articles/generating-ssh-keys/) to see how to set them up.

**Comment by btholt** [comment]
I'm going to close this issue as I don't think it's a problem with this repo. Let me know if that's not true.

**Comment by kezzbracey** [comment]
Just wanted to let you know I ran into the same issue when installing this via npm. I was installing alongside several other postcss plugins and unfortunately it seems only this one caused the error message.

```
npm ERR! Command failed: git clone --template=/Users/kezzb/.npm/_git-remotes/_templates --mirror ssh://git@github.com/btholt/hex-color-regex.git /Users/kezzb/.npm/_git-remotes/ssh-git-github-com-btholt-hex-color-regex-git-2ab14d10
npm ERR! Cloning into bare repository '/Users/kezzb/.npm/_git-remotes/ssh-git-github-com-btholt-hex-color-regex-git-2ab14d10'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

I checked on my SSH keys, and to the best of my understanding, they seem to be okay.

If it's any help, I took a quick look at the package.json files of the other plugins that "npm"d in okay, and I noticed they don't seem to have `git+` at the beginning of their repository URLs. I'm a git noob and have no clue what this means, but I thought it might help.

This was the command I used:

`npm install lost postcss-colorblind rtlcss postcss-modular-scale postcss-class-prefix postcss-pxtorem postcss-style-guide --save-dev`

With postcss-colorblind out of the command the others installed okay.

If I can help with any other tests or anything, give me a shout.

**Comment by kezzbracey** [comment]
Update: I came back and tried again today, having changed nothing, and it worked via npm install. There was definitely an issue yesterday though as I tried multiple times. Weird. :-/

**Comment by btholt** [comment]
😯 If you run into again, let me know.

**Comment by KezzB** [comment]
Will do! Btw I'm writing about your plugin for a tutorial to go on webdesign.tutsplus.com. If you want to look out for it, it will be part of a series called PostCSS Deep Dive.

**Comment by btholt** [comment]
Neat! Let me know if I can be of any help.
